title: "React Native Tutorial"
remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs
# Enable or disable the site search
# Support true (default) or false
search_enabled: true
# Aux links for the upper right navigation
aux_links:
    "React Native Tutorial on Github":
      - "//github.com/JeffGuKang/react-native-tutorial"
# Heading anchor links appear on hover over h1-h6 tags
# in page content allowing users to deep link to a particular
# heading on a page.
#
# Supprts true (default) or false/nil
heading_anchors: true
footer_content: "<a href=\"https://github.com/JeffGuKang/react-native-tutorial\">Github</a>"
# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-147391080-1

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blank_lines: false
  profile: false

# Exclude list
exclude: ['_site', 'node_modules', 'Examples', 'Gemfile', 'Gemfile.lock', 'READMD.md']
